pipeline {
    agent any

    tools {
        maven "Maven3"
    }

    environment {
        PATH = "/usr/local/bin/docker"
        DOCKERHUB_CREDENTIALS_ID = 'docker_hub'
        DOCKERHUB_REPO = 'sandra-sanj/otp1_assignments'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "https://github.com/sandra-sanj/otp1_assignments.git", branch: "main"
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage("Build") {
            steps {
                sh "mvn clean install"
            }
        }

        stage("Code Coverage") {
            steps {
                sh "mvn jacoco:report"
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }
    }
}